config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root "dumps#index"

  resources :dumps do
    collection do
      get 'search'
    end
    resources :dump_comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  resources :buys do
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
    resources :hates, only: [:create, :destroy]
  end

  resources :users, only: [:show] do
    member do
      get 'mydump'
      get 'mybuy'
      get 'dumpsearch'
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'は「aaa@bbb.ccc」の形式で入力してください' }

  has_many :buys, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :hates, dependent: :destroy
  has_many :dumps, dependent: :destroy
  has_many :dump_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def self.set_hate_count(user)
    buys = user.buys
    buy_id = []
    buys.each do |buy|
      buy_id << buy.id
    end
    Hate.where(buy_id: buy_id).count
  end

  def self.set_like_count(user)
    dumps = user.dumps
    dump_id = []
    dumps.each do |dump|
      dump_id << dump.id
    end
    Like.where(dump_id: dump_id).count
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def after_sign_in_path_for(_resource)
    root_path
  end

  def after_update_path_for(_resource)
    user_path(id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :mydump, :mybuy, :dumpsearch, :search]

  def show
    @hate_count = User.set_hate_count(@user)
    @dump_count = User.set_like_count(@user)
  end

  def mydump
    @dumps = params[:tag_id].present? ? Tag.find(params[:tag_id]).dumps.includes(:user) : Dump.includes(:user)
  end

  def mybuy
    @buys = params[:tag_id].present? ? Tag.find(params[:tag_id]).buys.includes(:user) : Buy.includes(:user)
  end

  def dumpsearch
    @dumps = Dump.search(params[:keyword])
  end

  def search
    @buys = Buy.search(params[:keyword])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_buy.html.haml
.item-area
  .item-area__item.title-box
    = "#{@user.name}さんの『購入品』一覧"
  = render partial: "shared/search", locals: {tagpath: mybuy_user_path(current_user.id), searchpath: search_user_path(current_user.id)}

.buy
  - @buys.each do |buy|
    - if buy.user_id == @user.id
      .buy__item{:style => "background-image: url(#{buy.image.url})"}
        .buy__item-top
          .buy__item-top.item-title
            = buy.goods
          .buy__item-top.item-bar
            = icon('fas fa-caret-down', class: "menu-icon")
            %ul.more-list
              %li
                = link_to "SHOW", buy_path(buy.id), method: :get
              %li
                = link_to "EDIT", edit_buy_path(buy.id), method: :get
              %li
                = link_to "DELETE", buy_path(buy.id), method: :delete, data: { confirm: "本当に投稿を削除しますか?" } 
        .buy__item-bottom
          .buy__item-bottom.item-icon
            %div{id: "hate-#{buy.id}", class: "buy__item-bottom item-icon__hate"}
              = render partial: "hates/hate", locals: {buy: buy}
            .buy__item-bottom.item-icon__comment
              - if user_signed_in?
                = link_to buy_path(buy.id), method: :get do
                  = icon('fas fa-comment-alt', class: "comment-icon")
              - else
                = icon('fas fa-comment-alt', class: "comment-icon")
              .buy__item-bottom.item-icon__comment-count
                = buy.comments.count
          .buy__item-bottom.item-writer
            = buy.user.name

app/views/users/shared/_dump.html.haml
.item-area
  .item-area__item.title-box
    = "#{@user.name}さんの『断捨離』一覧"
  = render partial: "shared/search", locals: {tagpath: mydump_user_path(current_user.id), searchpath: dumpsearch_user_path(current_user.id)}

.buy
  - @dumps.each do |dump|
    - if dump.user_id == @user.id
      .buy__item{:style => "background-image: url(#{dump.image.url})"}
        .buy__item-top
          .buy__item-top.item-title
            = dump.goods
          .buy__item-top.item-bar
            = icon('fas fa-caret-down', class: "menu-icon")
            %ul.more-list
              %li
                = link_to "SHOW", dump_path(dump.id), method: :get
              %li
                = link_to "EDIT", edit_dump_path(dump.id), method: :get
              %li
                = link_to "DELETE", dump_path(dump.id), method: :delete, data: { confirm: "本当に投稿を削除しますか?" } 
        .buy__item-bottom
          .buy__item-bottom.item-icon
            %div{id: "hate-#{dump.id}", class: "buy__item-bottom item-icon__hate"}
              = render partial: "likes/like", locals: {dump: dump}
            .buy__item-bottom.item-icon__comment
              - if user_signed_in?
                = link_to dump_path(dump.id), method: :get do
                  = icon('fas fa-comment-alt', class: "comment-icon")
              - else
                = icon('fas fa-comment-alt', class: "comment-icon")
              .buy__item-bottom.item-icon__comment-count
                = dump.dump_comments.count
          .buy__item-bottom.item-writer
            = dump.user.name

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/