config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root "dumps#index"

  resources :dumps do
    collection do
      get 'search'
    end
    resources :dump_comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  resources :buys do
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
    resources :hates, only: [:create, :destroy]
  end

  resources :users, only: [:show] do
    member do
      get 'mydump'
      get 'mybuy'
      get 'dumpsearch'
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
  belongs_to :user
  has_many :buy_tags, dependent: :destroy
  has_many :tags, through: :buy_tags
  has_many :comments, dependent: :destroy
  has_many :hates, dependent: :destroy

  with_options presence: true do
    validates :goods
    validates :price
    validates :description
  end

  validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }

  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :buy_tags, allow_destroy: true
  validates_associated :buy_tags, message: 'を選択してください'
  validates :buy_tags, presence: true

  scope :search, ->(search) { where('goods LIKE(?)', "%#{search}%") }
end

app/models/buy_tag.rb
class BuyTag < ApplicationRecord
  belongs_to :buy
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :buy

  validates :text, presence: true
end

app/models/dump.rb
class Dump < ApplicationRecord
  belongs_to :user
  has_many :dump_tags, dependent: :destroy
  has_many :tags, through: :dump_tags
  has_many :dump_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  with_options presence: true do
    validates :goods
    validates :price
    validates :description
  end

  validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }

  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :dump_tags, allow_destroy: true
  validates_associated :dump_tags, message: 'を選択してください'
  validates :dump_tags, presence: true

  scope :search, ->(search) { where('goods LIKE(?)', "%#{search}%") }
end

app/models/dump_comment.rb
class DumpComment < ApplicationRecord
  belongs_to :user
  belongs_to :dump

  validates :text, presence: true
end

app/models/dump_tag.rb
class DumpTag < ApplicationRecord
  belongs_to :dump
  belongs_to :tag
end

app/models/hate.rb
class Hate < ApplicationRecord
  belongs_to :user
  belongs_to :buy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :dump
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :buy_tags, dependent: :destroy
  has_many :buys, through: :buy_tags
  has_many :dump_tags, dependent: :destroy
  has_many :dumps, through: :dump_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'は「aaa@bbb.ccc」の形式で入力してください' }

  has_many :buys, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :hates, dependent: :destroy
  has_many :dumps, dependent: :destroy
  has_many :dump_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def self.set_hate_count(user)
    buys = user.buys
    buy_id = []
    buys.each do |buy|
      buy_id << buy.id
    end
    Hate.where(buy_id: buy_id).count
  end

  def self.set_like_count(user)
    dumps = user.dumps
    dump_id = []
    dumps.each do |dump|
      dump_id << dump.id
    end
    Like.where(dump_id: dump_id).count
  end
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  def index
    @buys = params[:tag_id].present? ? Tag.find(params[:tag_id]).buys.includes(:user).order('created_at DESC').page(params[:page]).per(18) : Buy.includes(:user).order('created_at DESC').page(params[:page]).per(18)
  end

  def new
    @buy = Buy.new
    @buy.buy_tags.build
  end

  def create
    @buy = Buy.new(buy_params)
    @buy.save
    render :new unless @buy.save
  end

  def show
    @comment = Comment.new
    @comments = @buy.comments.includes(:user)
  end

  def edit
    @buy.buy_tags
  end

  def update
    @buy.update(buy_params)
    render :edit unless @buy.update(buy_params)
  end

  def destroy
    @buy.destroy
  end

  def search
    @buys = Buy.search(params[:keyword]).order('created_at DESC').page(params[:page]).per(18)
  end

  private

  def buy_params
    params.require(:buy).permit(:goods, :price, :image, :description, buy_tags_attributes: [:buy_id, :tag_id, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_buy
    @buy = Buy.find(params[:id])
  end
end

app/controllers/dumps_controller.rb
class DumpsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_dump, only: [:show, :edit, :update, :destroy]

  def index
    @dumps = params[:tag_id].present? ? Tag.find(params[:tag_id]).dumps.includes(:user).order('created_at DESC').page(params[:page]).per(18) : Dump.includes(:user).order('created_at DESC').page(params[:page]).per(18)
  end

  def new
    @dump = Dump.new
    @dump.dump_tags.build
  end

  def create
    @dump = Dump.new(dump_params)
    @dump.save
    render :new unless @dump.save
  end

  def show
    @comment = DumpComment.new
    @comments = @dump.dump_comments.includes(:user)
  end

  def edit
    @dump.dump_tags
  end

  def update
    @dump.update(dump_params)
    render :edit unless @dump.update(dump_params)
  end

  def destroy
    @dump.destroy
  end

  def search
    @dumps = Dump.search(params[:keyword]).order('created_at DESC').page(params[:page]).per(18)
  end

  private

  def dump_params
    params.require(:dump).permit(:goods, :price, :image, :description, dump_tags_attributes: [:dump_id, :tag_id, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_dump
    @dump = Dump.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_menu_list(instance)
    user_signed_in? && current_user.id == instance.user_id
  end
end

app/helpers/buys_helper.rb
module BuysHelper
  def link_to_index_buy
    link_to '投稿一覧に戻る', buys_path, class: 'move-index__btn'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dumps_helper.rb
module DumpsHelper
  def link_to_index_dump
    link_to '投稿一覧に戻る', dumps_path, class: 'move-index__btn'
  end
end

app/helpers/hates_helper.rb
module HatesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Minimum
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "shared/header"
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/shared/_buyform.html.haml
.send-buy__form.form__buy
  = form_for [@buy], html: {class: "form__area"} do |f|
    .send__buy
      - if @buy.errors.any?
        %ul
          %li.error__messages
            = @buy.errors.full_messages_for(:goods).first
      = f.text_field :goods, class: "send__buy-goods", placeholder: "購入品 （例）MacBook"
      - if @buy.errors.any?
        %ul
          %li.error__messages
            = @buy.errors.full_messages_for(:price).first
      = f.text_field :price, class: "send__buy-price", placeholder: "購入金額 （例）150000"
      - if @buy.errors.any?
        %ul
          %li.error__messages
            = @buy.errors.full_messages_for(:buy_tags).first
      = f.fields_for :buy_tags do |t|
        = t.collection_select :tag_id, Tag.all, :id, :name, include_blank: '選択してください'
      = f.label :image, class: "send__buy-image" do
        = icon('fas', 'image', class: "send__buy-image__icon")
        写真を選択してください
        = f.file_field :image, class: "send__buy-image__field"
      - if @buy.errors.any?
        %ul
          %li.error__messages
            = @buy.errors.full_messages_for(:description).first
      = f.text_area :description, class: "send__buy-description", rows: "10", placeholder: "購入した理由 （例）プログラミング学習をするために、購入しました。"
      = f.submit "Send", class: "send__buy-submit"

app/views/shared/_buyindex.html.haml
.item-area
  .item-area__item.title-box
    みんなの購入品はどんなもの？
  = render partial: "shared/search", locals: {tagpath: buys_path, searchpath: search_buys_path}

.buy
  - @buys.each do |buy|
    .buy__item{:style => "background-image: url(#{buy.image.url})"}
      .buy__item-top
        .buy__item-top.item-title
          = buy.goods
        .buy__item-top.item-bar
          = icon('fas fa-caret-down', class: "menu-icon")
          %ul.more-list
            %li
              = link_to "SHOW", buy_path(buy.id), method: :get
            - if user_menu_list(buy)
              %li
                = link_to "EDIT", edit_buy_path(buy.id), method: :get
              %li
                = link_to "DELETE", buy_path(buy.id), method: :delete, data: { confirm: "本当に投稿を削除しますか?" } 
      .buy__item-bottom
        .buy__item-bottom.item-icon
          %div{id: "hate-#{buy.id}", class: "buy__item-bottom item-icon__hate"}
            = render partial: "hates/hate", locals: {buy: buy}
          .buy__item-bottom.item-icon__comment
            - if user_signed_in?
              = link_to buy_path(buy.id), method: :get do
                = icon('fas fa-comment-alt', class: "comment-icon")
            - else
              = icon('fas fa-comment-alt', class: "comment-icon")
            .buy__item-bottom.item-icon__comment-count
              = buy.comments.count
        .buy__item-bottom.item-writer
          = buy.user.name
= paginate(@buys)

app/views/shared/_dumpform.html.haml
.send-buy__form.form__buy
  = form_for [@dump], html: {class: "form__area"} do |f|
    .send__buy
      - if @dump.errors.any?
        %ul
          %li.error__messages
            = @dump.errors.full_messages_for(:goods).first
      = f.text_field :goods, class: "send__buy-goods", placeholder: "断捨離品 （例）洋服"
      - if @dump.errors.any?
        %ul
          %li.error__messages
            = @dump.errors.full_messages_for(:price).first
      = f.text_field :price, class: "send__buy-price", placeholder: "購入時の金額 （例）15000"
      - if @dump.errors.any?
        %ul
          %li.error__messages
            = @dump.errors.full_messages_for(:dump_tags).first
      = f.fields_for :dump_tags do |t|
        = t.collection_select :tag_id, Tag.all, :id, :name, include_blank: '選択してください'
      = f.label :image, class: "send__buy-image" do
        = icon('fas', 'image', class: "send__buy-image__icon")
        写真を選択してください
        = f.file_field :image, class: "send__buy-image__field"
      - if @dump.errors.any?
        %ul
          %li.error__messages
            = @dump.errors.full_messages_for(:description).first
      = f.text_area :description, class: "send__buy-description", rows: "10", placeholder: "断捨離した理由 （例）同じような洋服を何枚も持っているため、断捨離しました。"
      = f.submit "Send", class: "send__buy-submit"

app/views/shared/_dumpindex.html.haml
.item-area
  .item-area__item.title-box
    みんなの断捨離はどんなもの？
  = render partial: "shared/search", locals: {tagpath: dumps_path, searchpath: search_dumps_path}

.buy
  - @dumps.each do |dump|
    .buy__item{:style => "background-image: url(#{dump.image.url})"}
      .buy__item-top
        .buy__item-top.item-title
          = dump.goods
        .buy__item-top.item-bar
          = icon('fas fa-caret-down', class: "menu-icon")
          %ul.more-list
            %li
              = link_to "SHOW", dump_path(dump.id), method: :get
            - if user_menu_list(dump)
              %li
                = link_to "EDIT", edit_dump_path(dump.id), method: :get
              %li
                = link_to "DELETE", dump_path(dump.id), method: :delete, data: { confirm: "本当に投稿を削除しますか?" } 
      .buy__item-bottom
        .buy__item-bottom.item-icon
          %div{id: "hate-#{dump.id}", class: "buy__item-bottom item-icon__hate"}
            = render partial: "likes/like", locals: {dump: dump}
          .buy__item-bottom.item-icon__comment
            - if user_signed_in?
              = link_to dump_path(dump.id), method: :get do
                = icon('fas fa-comment-alt', class: "comment-icon")
            - else
              = icon('fas fa-comment-alt', class: "comment-icon")
            .buy__item-bottom.item-icon__comment-count
              = dump.dump_comments.count
        .buy__item-bottom.item-writer
          = dump.user.name
= paginate(@dumps)

app/views/shared/_header.html.haml
.top-image
  .top-image__title
    Minimum
  .top-image__sub-title
    それって、本当に必要なの？

.menu-bar
  = link_to "『断捨離』", dumps_path, class: "menu-bar__item discard-list"
  = link_to "『購入品』", buys_path, class: "menu-bar__item buy-list"
  - if user_signed_in?
    = link_to "My page", user_path(current_user.id), class: "menu-bar__item Mypage"
    = link_to "Log out", destroy_user_session_path, method: :delete, class: "menu-bar__item Logout"
  - else
    = link_to "Sign up", new_user_registration_path, class: "menu-bar__item Signup"
    = link_to "Log in", new_user_session_path, class: "menu-bar__item Login"

app/views/shared/_mypage.html.haml
.mypage__side-area
  .mypage__side-area__title
    My menu
  .mypage__side-area__item.my-discard
    = link_to "My『断捨離』", mydump_user_path(current_user.id)
  .mypage__side-area__item.send-discard
    = link_to "Send『断捨離』", new_dump_path
  .mypage__side-area__item.my-buy
    = link_to "My『購入品』", mybuy_user_path(current_user.id)
  .mypage__side-area__item.send-buy
    = link_to "Send『購入品』", new_buy_path
  .mypage__side-area__item.setting-user
    =link_to "Edit account", edit_user_registration_path
  .mypage__side-area__item.delete-user
    = link_to "Leave Minimum", user_registration_path, method: :delete, data: { confirm: "Minimumを退会しますか?　退会をすると、全てのデータが失われます。" } 

app/views/shared/_search.html.haml
.item-area__item.search-box
  .item-area__item.search-box__tag
    = form_with url: tagpath, local: true, method: :get, class: "search-tag" do |f|
      = select_tag :tag_id, options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]), {prompt: "タグで絞り込み検索", onchange: 'submit(this.form);'}
  .item-area__item.search-box__free
    = form_with url: searchpath, local: true, method: :get, class: "search-form" do |f|
      = f.text_field :keyword, class: "search-input", placeholder: "フリーワード検索"
      = f.submit "検索", class: "search-btn"