config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root "dumps#index"

  resources :dumps do
    collection do
      get 'search'
    end
    resources :dump_comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  resources :buys do
    collection do
      get 'search'
    end
    resources :comments, only: [:create]
    resources :hates, only: [:create, :destroy]
  end

  resources :users, only: [:show] do
    member do
      get 'mydump'
      get 'mybuy'
      get 'dumpsearch'
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buy.rb
class Buy < ApplicationRecord
  belongs_to :user
  has_many :buy_tags, dependent: :destroy
  has_many :tags, through: :buy_tags
  has_many :comments, dependent: :destroy
  has_many :hates, dependent: :destroy

  with_options presence: true do
    validates :goods
    validates :price
    validates :description
  end

  validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }

  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :buy_tags, allow_destroy: true
  validates_associated :buy_tags, message: 'を選択してください'
  validates :buy_tags, presence: true

  scope :search, ->(search) { where('goods LIKE(?)', "%#{search}%") }
end

app/models/buy_tag.rb
class BuyTag < ApplicationRecord
  belongs_to :buy
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :buy

  validates :text, presence: true
end

app/models/dump.rb
class Dump < ApplicationRecord
  belongs_to :user
  has_many :dump_tags, dependent: :destroy
  has_many :tags, through: :dump_tags
  has_many :dump_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  with_options presence: true do
    validates :goods
    validates :price
    validates :description
  end

  validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }

  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :dump_tags, allow_destroy: true
  validates_associated :dump_tags, message: 'を選択してください'
  validates :dump_tags, presence: true

  scope :search, ->(search) { where('goods LIKE(?)', "%#{search}%") }
end

app/models/dump_comment.rb
class DumpComment < ApplicationRecord
  belongs_to :user
  belongs_to :dump

  validates :text, presence: true
end

app/models/dump_tag.rb
class DumpTag < ApplicationRecord
  belongs_to :dump
  belongs_to :tag
end

app/models/hate.rb
class Hate < ApplicationRecord
  belongs_to :user
  belongs_to :buy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :dump
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :buy_tags, dependent: :destroy
  has_many :buys, through: :buy_tags
  has_many :dump_tags, dependent: :destroy
  has_many :dumps, through: :dump_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'は「aaa@bbb.ccc」の形式で入力してください' }

  has_many :buys, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :hates, dependent: :destroy
  has_many :dumps, dependent: :destroy
  has_many :dump_comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def self.set_hate_count(user)
    buys = user.buys
    buy_id = []
    buys.each do |buy|
      buy_id << buy.id
    end
    Hate.where(buy_id: buy_id).count
  end

  def self.set_like_count(user)
    dumps = user.dumps
    dump_id = []
    dumps.each do |dump|
      dump_id << dump.id
    end
    Like.where(dump_id: dump_id).count
  end
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  def index
    @buys = params[:tag_id].present? ? Tag.find(params[:tag_id]).buys.includes(:user).order('created_at DESC').page(params[:page]).per(18) : Buy.includes(:user).order('created_at DESC').page(params[:page]).per(18)
  end

  def new
    @buy = Buy.new
    @buy.buy_tags.build
  end

  def create
    @buy = Buy.new(buy_params)
    @buy.save
    render :new unless @buy.save
  end

  def show
    @comment = Comment.new
    @comments = @buy.comments.includes(:user)
  end

  def edit
    @buy.buy_tags
  end

  def update
    @buy.update(buy_params)
    render :edit unless @buy.update(buy_params)
  end

  def destroy
    @buy.destroy
  end

  def search
    @buys = Buy.search(params[:keyword]).order('created_at DESC').page(params[:page]).per(18)
  end

  private

  def buy_params
    params.require(:buy).permit(:goods, :price, :image, :description, buy_tags_attributes: [:buy_id, :tag_id, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_buy
    @buy = Buy.find(params[:id])
  end
end

app/controllers/dumps_controller.rb
class DumpsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_dump, only: [:show, :edit, :update, :destroy]

  def index
    @dumps = params[:tag_id].present? ? Tag.find(params[:tag_id]).dumps.includes(:user).order('created_at DESC').page(params[:page]).per(18) : Dump.includes(:user).order('created_at DESC').page(params[:page]).per(18)
  end

  def new
    @dump = Dump.new
    @dump.dump_tags.build
  end

  def create
    @dump = Dump.new(dump_params)
    @dump.save
    render :new unless @dump.save
  end

  def show
    @comment = DumpComment.new
    @comments = @dump.dump_comments.includes(:user)
  end

  def edit
    @dump.dump_tags
  end

  def update
    @dump.update(dump_params)
    render :edit unless @dump.update(dump_params)
  end

  def destroy
    @dump.destroy
  end

  def search
    @dumps = Dump.search(params[:keyword]).order('created_at DESC').page(params[:page]).per(18)
  end

  private

  def dump_params
    params.require(:dump).permit(:goods, :price, :image, :description, dump_tags_attributes: [:dump_id, :tag_id, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_dump
    @dump = Dump.find(params[:id])
  end
end

app/controllers/hates_controller.rb
class HatesController < ApplicationController
  before_action :set_buy, only: [:create, :destroy]

  def create
    @hate = Hate.create(user_id: current_user.id, buy_id: @buy.id)
  end

  def destroy
    @hate = Hate.find_by(user_id: current_user.id, buy_id: @buy.id)
    @hate.destroy
  end

  private

  def set_buy
    @buy = Buy.find(params[:buy_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_dump, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, dump_id: @dump.id)
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, dump_id: @dump.id)
    @like.destroy
  end

  private

  def set_dump
    @dump = Dump.find(params[:dump_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :mydump, :mybuy, :dumpsearch, :search]

  def show
    @hate_count = User.set_hate_count(@user)
    @dump_count = User.set_like_count(@user)
  end

  def mydump
    @dumps = params[:tag_id].present? ? Tag.find(params[:tag_id]).dumps.includes(:user) : Dump.includes(:user)
  end

  def mybuy
    @buys = params[:tag_id].present? ? Tag.find(params[:tag_id]).buys.includes(:user) : Buy.includes(:user)
  end

  def dumpsearch
    @dumps = Dump.search(params[:keyword])
  end

  def search
    @buys = Buy.search(params[:keyword])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_menu_list(instance)
    user_signed_in? && current_user.id == instance.user_id
  end
end

app/helpers/buys_helper.rb
module BuysHelper
  def link_to_index_buy
    link_to '投稿一覧に戻る', buys_path, class: 'move-index__btn'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dumps_helper.rb
module DumpsHelper
  def link_to_index_dump
    link_to '投稿一覧に戻る', dumps_path, class: 'move-index__btn'
  end
end

app/helpers/hates_helper.rb
module HatesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buys/create.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .buys-function__title
      投稿が完了しました
    .buys-function__subtitle
      = link_to_index_buy

app/views/buys/destroy.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .buys-function__title
      投稿を削除しました
    .buys-function__subtitle
      = link_to_index_buy

app/views/buys/edit.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .send-buy__form.form__title
      = icon("fas fa-shopping-cart", class: "shopping-icon")
      購入品を編集する
    = render "/shared/buyform"

app/views/buys/index.html.haml
= render "shared/buyindex"

app/views/buys/new.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .send-buy__form.form__title
      = icon("fas fa-shopping-cart", class: "shopping-icon")
      購入品を投稿する
    = render "/shared/buyform"

app/views/buys/search.html.haml
= render "shared/buyindex"

app/views/buys/show.html.haml
.buy-show
  .buy-show__image{:style => "background-image: url(#{@buy.image.url})"}
    .buy-show__image-bar
      = icon('fas fa-caret-down', class: "menu-icon")
      - if user_menu_list(@buy)
        %ul.more-list
          %li
            = link_to "EDIT", edit_buy_path(@buy.id), method: :get
          %li
            = link_to "DELETE", buy_path(@buy.id), method: :delete, data: { confirm: "本当に投稿を削除しますか?" } 
    .buy-show__image-icon
      .buy-show__image-icon__hate
        %div{id: "hate-#{@buy.id}", class: "buy__item-bottom item-icon__hate"}
          = render partial: "hates/hate", locals: {buy: @buy}
      .buy-show__image-icon__comment
        = icon('fas fa-comment-alt', class: "comment-icon")
        = @buy.comments.count
  .buy-show__list
    %table
      %tr
        %th.buy-show__item-bottom.show-writer
          投稿者
        %td.buy-show__item-bottom.show-writer
          = @buy.user.name
      %tr
        %th.buy-show__list-title
          購入品
        %td.buy-show__list-title
          = @buy.goods
      %tr
        %th.buy-show__list-tag
          タグ
        %td.buy-show__list-tag
          - @buy.tags.each do |tag|
            = tag.name
      %tr
        %th.buy-show__list-price
          購入金額
        %td.buy-show__list-price
          = "#{@buy.price}円"
      %tr
        %th.buy-show__list-description
          購入した理由
        %td.buy-show__list-description
          = @buy.description

.buy-comment
  - if current_user
    .buy-comment__send
      = form_for [@buy, @comment], html: {class: "buy-comment__send-form", id: "buy-comment__send-form"} do |f|
        = f.text_area :text, class: "buy-comment__send-text", placeholder: "コメントをする"
        = f.submit "SEND", class: "buy-comment__send-submit"
  .buy-comment__title
    〈コメント一覧〉
    - if @comments
      .ajax
        - @comments.each do |comment|
          .buy-comment__list
            .buy-comment__list-writter
              = "#{comment.user.name}:"
            .buy-comment__list-comment
              = comment.text

app/views/buys/update.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .buys-function__title
      編集が完了しました
    .buys-function__subtitle
      = link_to_index_buy

app/views/dumps/create.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .buys-function__title
      投稿が完了しました
    .buys-function__subtitle
      = link_to_index_dump

app/views/dumps/destroy.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .buys-function__title
      投稿を削除しました
    .buys-function__subtitle
      = link_to_index_dump

app/views/dumps/edit.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .send-buy__form.form__title
      = icon("fas fa-shopping-cart", class: "shopping-icon")
      断捨離を編集する
    = render "/shared/dumpform"

app/views/dumps/index.html.haml
= render "shared/dumpindex"

app/views/dumps/new.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .send-buy__form.form__title
      = icon("fas fa-trash-alt", class: "garbage-icon")
      断捨離を投稿する
    = render "/shared/dumpform"

app/views/dumps/search.html.haml
= render "shared/dumpindex"

app/views/dumps/show.html.haml
.buy-show
  .buy-show__image{:style => "background-image: url(#{@dump.image.url})"}
    .buy-show__image-bar
      = icon('fas fa-caret-down', class: "menu-icon")
      - if user_menu_list(@dump)
        %ul.more-list
          %li
            = link_to "EDIT", edit_dump_path(@dump.id), method: :get
          %li
            = link_to "DELETE", dump_path(@dump.id), method: :delete, data: { confirm: "本当に投稿を削除しますか?" } 
    .buy-show__image-icon
      .buy-show__image-icon__hate
        %div{id: "hate-#{@dump.id}", class: "buy__item-bottom item-icon__hate"}
          = render partial: "likes/like", locals: {dump: @dump}
      .buy-show__image-icon__comment
        = icon('fas fa-comment-alt', class: "comment-icon")
        = @dump.dump_comments.count
  .buy-show__list
    %table
      %tr
        %th.buy-show__item-bottom.show-writer
          投稿者
        %td.buy-show__item-bottom.show-writer
          = @dump.user.name
      %tr
        %th.buy-show__list-title
          断捨離品
        %td.buy-show__list-title
          = @dump.goods
      %tr
        %th.buy-show__list-tag
          タグ
        %td.buy-show__list-tag
          - @dump.tags.each do |tag|
            = tag.name
      %tr
        %th.buy-show__list-price
          購入時金額
        %td.buy-show__list-price
          = "#{@dump.price}円"
      %tr
        %th.buy-show__list-description
          断捨離の理由
        %td.buy-show__list-description
          = @dump.description

.buy-comment
  - if current_user
    .buy-comment__send
      = form_for [@dump, @comment], html: {class: "buy-comment__send-form", id: "dump-comment__send-form"} do |f|
        = f.text_area :text, class: "buy-comment__send-text", placeholder: "コメントをする"
        = f.submit "SEND", class: "buy-comment__send-submit"
  .buy-comment__title
    〈コメント一覧〉
    - if @comments
      .ajax
        - @comments.each do |comment|
          .buy-comment__list
            .buy-comment__list-writter
              = "#{comment.user.name}:"
            .buy-comment__list-comment
              = comment.text

app/views/dumps/update.html.haml
.send-buy__page
  = render "shared/mypage"
  .send-buy__form
    .buys-function__title
      編集が完了しました
    .buys-function__subtitle
      = link_to_index_dump

app/views/hates/_hate.html.haml
- if user_signed_in?
  - if Hate.find_by(user_id: current_user.id, buy_id: buy.id)
    = link_to buy_hate_path(buy, buy.id), class: "hate-path", method: :delete, remote: true do
      = icon('fas fa-thumbs-down', class: "hate-icon")
  - else
    = link_to buy_hates_path(buy), method: :post, class: "hate-path", remote: true do
      = icon('far fa-thumbs-down', class: "hate-icon")
  .item-icon__hate-count
    = buy.hates.count
- else
  = icon('fas fa-thumbs-down', class: "hate-icon")
  .item-icon__hate-count
    = buy.hates.count

app/views/hates/_hates.html.haml
- if buy.hate_user(current_user.id)
  = link_to buy_hates_path(buy, buy.hate_user(current_user)), method: :delete, remote: true do
    = icon('fas fa-heart-broken', class: "hate-icon")
- else
  = link_to buy_hates_path(buy), method: :post, remote: true do
    = icon('fas fa-heart-broken', class: "hate-icon")

app/views/hates/create.js.erb
$('#hate-<%= @buy.id %>').html("<%= j(render partial: 'hates/hate', locals: {buy: @buy}) %>");

app/views/hates/destroy.js.erb
$('#hate-<%= @buy.id %>').html("<%= j(render partial: 'hates/hate', locals: {buy: @buy}) %>");

app/views/likes/_like.html.haml
- if user_signed_in?
  - if Like.find_by(user_id: current_user.id, dump_id: dump.id)
    = link_to dump_like_path(dump, dump.id), class: "like-path", method: :delete, remote: true do
      = icon('fas fa-thumbs-up', class: "hate-icon")
  - else
    = link_to dump_likes_path(dump), class: "like-path", method: :post, remote: true do
      = icon('far fa-thumbs-up', class: "hate-icon")
  .item-icon__hate-count
    = dump.likes.count
- else
  = icon('fas fa-thumbs-up', class: "hate-icon")
  .item-icon__hate-count
    = dump.likes.count

app/views/likes/create.js.erb
$('#hate-<%= @dump.id %>').html("<%= j(render partial: 'likes/like', locals: {dump: @dump}) %>");

app/views/likes/destroy.js.erb
$('#hate-<%= @dump.id %>').html("<%= j(render partial: 'likes/like', locals: {dump: @dump}) %>");